version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Password1*
    ports:
      - 5432:5432

  message-broker:
    image: rabbitmq:management-alpine
#    container_name: app-message-broker
    ports:
      - 5672:5672
      - 15672:15672
    # volumes:
    restart: always
    networks:
      - dev-network

networks:
  dev-network:
